/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import control.ControlSonidoAdministrador;
import control.ControlSonidos;
import control.ControlSubidosAdminPorCategoria;
import java.awt.Image;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import modelo.SonidoAdministrador;
import modelo.Sonidos;
import modelo.SubidosAdminPorCategoria;
/**
 *
 * @author Carlos
 */
public class ConsultarSonidos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarSonidos
     */
    LinkedList<SonidoAdministrador> listaSonidosAdmin;
    LinkedList<Sonidos> listaSonidos;
    LinkedList<SubidosAdminPorCategoria> listaSubidosAdmin;
    
    public ConsultarSonidos() {
        initComponents();
        listaSonidosAdmin = new LinkedList<>();
        listaSonidos = new LinkedList<>();
        listaSubidosAdmin = new LinkedList<>();
        imagen();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consultar Sonidos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sonidos Usuario");

        jTextField3.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButton4.setText("Mostrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario", "Todos" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de usuario");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Nombre");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Fecha");

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Volver");

        jLabel6.setText("Elija una opcion para buscar");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("CategoriaSoloAdmin");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("CategoriaTodos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1)))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ControlSonidoAdministrador objCsa = new ControlSonidoAdministrador();
        int ncol;
        Object[] fila;
            if (jComboBox1.getSelectedIndex() == 0) {
            listaSonidosAdmin = objCsa.buscarSonidosAdministrador();

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            modelo.addColumn("Visualizacion");
            modelo.addColumn("Duracion");
            modelo.addColumn("Usuario");
            modelo.addColumn("Sonido");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("idCategoria");
            modelo.addColumn("idAdministrador");
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSonidosAdmin.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidosAdmin.get(i).isSonidosAdminPublicoPrivado();
                
                if(listaSonidosAdmin.get(i).isSonidosAdminPublicoPrivado() == true){
                fila[0] = "Publico";
                }else{
                    fila[0] = "Privado";
                }
                
                fila[1] = listaSonidosAdmin.get(i).getDuracionSonidoAdmin();
                fila[2] = listaSonidosAdmin.get(i).getAdminCreador();
                fila[3] = listaSonidosAdmin.get(i).getArchivoSonidoAdmin();
                fila[4] = listaSonidosAdmin.get(i).getDescripcionSonidoAdmin();
                fila[5] = listaSonidosAdmin.get(i).getFechaCreacionAdmin();
                fila[6] = listaSonidosAdmin.get(i).getPrecioAdmin();
                fila[7] = listaSonidosAdmin.get(i).getIdCategoriaf();
                fila[8] = listaSonidosAdmin.get(i).getIdAdminf();

                modelo.addRow(fila);
            }
          } else if(jComboBox1.getSelectedIndex() == 1){
            ControlSonidos objCs = new ControlSonidos();
            
            listaSonidos = objCs.buscarSonidos();

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            
            modelo.addColumn("idSonido");
            modelo.addColumn("Visualizacion");
            modelo.addColumn("Duracion");
            modelo.addColumn("Usuario");
            modelo.addColumn("Sonido");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("idLibreria");
            modelo.addColumn("idCategoria");
            modelo.addColumn("Cedula");
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSonidos.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidos.get(i).getIdSonido();
                fila[1] = listaSonidos.get(i).isSonidoPublicoPrivado();
                
                if(listaSonidos.get(i).isSonidoPublicoPrivado() == true){
                    fila[1] = "Publico";
                }else{
                    fila[1] = "Privado";
                }
                
                fila[2] = listaSonidos.get(i).getDuracionSonido();
                fila[3] = listaSonidos.get(i).getSubidoPor();
                fila[4] = listaSonidos.get(i).getArchivoSonido();
                fila[5] = listaSonidos.get(i).getDescripcionSonido();
                fila[6] = listaSonidos.get(i).getFechaCreacion();
                fila[7] = listaSonidos.get(i).getPrecioS();
                fila[8] = listaSonidos.get(i).getIdLibreriaf();
                fila[9] = listaSonidos.get(i).getIdCategoriaf();
                fila[10] = listaSonidos.get(i).getCedulaf();

                modelo.addRow(fila);
                ContarSonidos();
            }
          }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ControlSonidos objCs = new ControlSonidos();
        int ncol;
        Object[] fila;  
        if(jRadioButton1.isSelected() && jComboBox1.getSelectedIndex() == 1){
        String nombre = jTextField4.getText();
            listaSonidos = objCs.SonidosPorUsuario(nombre);

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            
            modelo.addColumn("idSonido");
            modelo.addColumn("Visualizacion");
            modelo.addColumn("Duracion");
            modelo.addColumn("Usuario");
            modelo.addColumn("Sonido");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("idLibreria");
            modelo.addColumn("idCategoria");
            modelo.addColumn("Cedula");
            ncol = modelo.getColumnCount();


            for (int i = 0; i < listaSonidos.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidos.get(i).getIdSonido();
                fila[1] = listaSonidos.get(i).isSonidoPublicoPrivado();
                
                if(listaSonidos.get(i).isSonidoPublicoPrivado() == true){
                    fila[1] = "Publico";
                }else{
                    fila[1] = "Privado";
                }
                
                fila[2] = listaSonidos.get(i).getDuracionSonido();
                fila[3] = listaSonidos.get(i).getSubidoPor();
                fila[4] = listaSonidos.get(i).getArchivoSonido();
                fila[5] = listaSonidos.get(i).getDescripcionSonido();
                fila[6] = listaSonidos.get(i).getFechaCreacion();
                fila[7] = listaSonidos.get(i).getPrecioS();
                fila[8] = listaSonidos.get(i).getIdLibreriaf();
                fila[9] = listaSonidos.get(i).getIdCategoriaf();
                fila[10] = listaSonidos.get(i).getCedulaf();

                modelo.addRow(fila);
                ContarSonidos();
            }
        } else if(jRadioButton1.isSelected() && jComboBox1.getSelectedIndex() == 0){
            ControlSonidoAdministrador objCsa = new ControlSonidoAdministrador();
            String nombre = jTextField4.getText();
            
            listaSonidosAdmin = objCsa.buscarSonidosAdministrador(nombre);

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            modelo.addColumn("Visualizacion");
            modelo.addColumn("Duracion");
            modelo.addColumn("Usuario");
            modelo.addColumn("Sonido");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("idCategoria");
            modelo.addColumn("idAdministrador");
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSonidosAdmin.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidosAdmin.get(i).isSonidosAdminPublicoPrivado();
                
                if(listaSonidosAdmin.get(i).isSonidosAdminPublicoPrivado() == true){
                fila[0] = "Publico";
                }else{
                    fila[0] = "Privado";
                }
                
                fila[1] = listaSonidosAdmin.get(i).getDuracionSonidoAdmin();
                fila[2] = listaSonidosAdmin.get(i).getAdminCreador();
                fila[3] = listaSonidosAdmin.get(i).getArchivoSonidoAdmin();
                fila[4] = listaSonidosAdmin.get(i).getDescripcionSonidoAdmin();
                fila[5] = listaSonidosAdmin.get(i).getFechaCreacionAdmin();
                fila[6] = listaSonidosAdmin.get(i).getPrecioAdmin();
                fila[7] = listaSonidosAdmin.get(i).getIdCategoriaf();
                fila[8] = listaSonidosAdmin.get(i).getIdAdminf();

                modelo.addRow(fila);
            }
        }else if(jRadioButton2.isSelected() && jComboBox1.getSelectedIndex() == 1){
            String fecha = jTextField4.getText();
            listaSonidos = objCs.SonidosPorFecha(fecha);

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            
            modelo.addColumn("idSonido");
            modelo.addColumn("Visualizacion");
            modelo.addColumn("Duracion");
            modelo.addColumn("Usuario");
            modelo.addColumn("Sonido");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("idLibreria");
            modelo.addColumn("idCategoria");
            modelo.addColumn("Cedula");
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSonidos.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidos.get(i).getIdSonido();
                fila[1] = listaSonidos.get(i).isSonidoPublicoPrivado();
                
                if(listaSonidos.get(i).isSonidoPublicoPrivado() == true){
                    fila[1] = "Publico";
                }else{
                    fila[1] = "Privado";
                }
                
                fila[2] = listaSonidos.get(i).getDuracionSonido();
                fila[3] = listaSonidos.get(i).getSubidoPor();
                fila[4] = listaSonidos.get(i).getArchivoSonido();
                fila[5] = listaSonidos.get(i).getDescripcionSonido();
                fila[6] = listaSonidos.get(i).getFechaCreacion();
                fila[7] = listaSonidos.get(i).getPrecioS();
                fila[8] = listaSonidos.get(i).getIdLibreriaf();
                fila[9] = listaSonidos.get(i).getIdCategoriaf();
                fila[10] = listaSonidos.get(i).getCedulaf();

                modelo.addRow(fila);
        }
       }else if(jRadioButton2.isSelected() && jComboBox1.getSelectedIndex() == 0){
           ControlSonidoAdministrador objCsa = new ControlSonidoAdministrador();
            String fecha = jTextField4.getText();
            
            listaSonidosAdmin = objCsa.SonidosPorFecha(fecha);

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            modelo.addColumn("Visualizacion");
            modelo.addColumn("Duracion");
            modelo.addColumn("Usuario");
            modelo.addColumn("Sonido");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Precio");
            modelo.addColumn("idCategoria");
            modelo.addColumn("idAdministrador");
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSonidosAdmin.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidosAdmin.get(i).isSonidosAdminPublicoPrivado();
                
                if(listaSonidosAdmin.get(i).isSonidosAdminPublicoPrivado() == true){
                fila[0] = "Publico";
                }else{
                    fila[0] = "Privado";
                }
                
                fila[1] = listaSonidosAdmin.get(i).getDuracionSonidoAdmin();
                fila[2] = listaSonidosAdmin.get(i).getAdminCreador();
                fila[3] = listaSonidosAdmin.get(i).getArchivoSonidoAdmin();
                fila[4] = listaSonidosAdmin.get(i).getDescripcionSonidoAdmin();
                fila[5] = listaSonidosAdmin.get(i).getFechaCreacionAdmin();
                fila[6] = listaSonidosAdmin.get(i).getPrecioAdmin();
                fila[7] = listaSonidosAdmin.get(i).getIdCategoriaf();
                fila[8] = listaSonidosAdmin.get(i).getIdAdminf();

                modelo.addRow(fila);
            }
       }else if(jComboBox1.getSelectedIndex() == 0 && jRadioButton3.isSelected()){
            ControlSubidosAdminPorCategoria objCpa = new ControlSubidosAdminPorCategoria();
            int n = Integer.parseInt(jTextField4.getText());
            
            listaSubidosAdmin = objCpa.buscarSubidosAdminPorCategoria(n);

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            
            modelo.addColumn("id");
            modelo.addColumn("Visualizacion");
            modelo.addColumn("usuarioAdmin");
            modelo.addColumn("nombre");
            modelo.addColumn("Sonido");
            
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSubidosAdmin.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSubidosAdmin.get(i).getIdCategoria();
                fila[1] = listaSubidosAdmin.get(i).isSonidosAdminPublicoPrivado();
                
                if(listaSubidosAdmin.get(i).isSonidosAdminPublicoPrivado() == true){
                    fila[1] = "Publico";
                }else{
                    fila[1] = "Privado";
                }
                
                fila[2] = listaSubidosAdmin.get(i).getUsuarioAdmin();
                fila[3] = listaSubidosAdmin.get(i).getAdminCreador();
                fila[4] = listaSubidosAdmin.get(i).getArchivoSonidoAdmin();

                modelo.addRow(fila);
            }
          }else if(jComboBox1.getSelectedIndex() == 2 && jRadioButton4.isSelected()){
            ControlSonidos objCso = new ControlSonidos();
            int n = Integer.parseInt(jTextField4.getText());
            
            listaSonidos = objCso.buscarSonidosCategoria(n);

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            
            modelo.addColumn("id");
            modelo.addColumn("Visualizacion");
            modelo.addColumn("duracion");
            modelo.addColumn("subidoPor");
            modelo.addColumn("archivo");
            modelo.addColumn("descripcion");
            modelo.addColumn("fechaCreacion");
            modelo.addColumn("precioS");
            modelo.addColumn("fechaCreacion");
            modelo.addColumn("idLibreriaf");
            modelo.addColumn("idCategoriaf");
            modelo.addColumn("cedulaf");
            
            ncol = modelo.getColumnCount();

            
            for (int i = 0; i < listaSonidos.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaSonidos.get(i).getIdSonido();
                fila[1] = listaSonidos.get(i).isSonidoPublicoPrivado();
                
                if(listaSonidos.get(i).isSonidoPublicoPrivado() == true){
                    fila[1] = "Publico";
                }else{
                    fila[1] = "Privado";
                }
                
                fila[2] = listaSonidos.get(i).getDuracionSonido();
                fila[3] = listaSonidos.get(i).getSubidoPor();
                fila[4] = listaSonidos.get(i).getArchivoSonido();
                fila[5] = listaSonidos.get(i).getDescripcionSonido();
                fila[6] = listaSonidos.get(i).getFechaCreacion();
                fila[7] = listaSonidos.get(i).getPrecioS();
                fila[8] = listaSonidos.get(i).getIdLibreriaf();
                fila[9] = listaSonidos.get(i).getIdCategoriaf();
                fila[10] = listaSonidos.get(i).getCedulaf();

                modelo.addRow(fila);
            } 
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        MenuAdmin Ma = new MenuAdmin();
        this.setVisible(false);
        Ma.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    public void ContarSonidos(){
          int filas = jTable1.getRowCount();
          jTextField3.setText("" + filas);
      }
    
    public void imagen(){
        ImageIcon imagen = new ImageIcon("src/Imagen/back-button.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_DEFAULT));
        jLabel5.setIcon(icono);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarSonidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarSonidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarSonidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarSonidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarSonidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
